services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend-php:
    build: ./backend-php
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: local
      APP_DEBUG: true
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  cache-node:
    build: ./cache-node
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASS: app
      DB_NAME: app
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8000
    depends_on:
      - backend-php
    ports:
      - "5173:5173"

volumes:
  dbdata:
